version: '3.7'

services:
  barot_pg:
    image: postgres:11
    container_name: barot_pg
    environment:
      POSTGRES_PASSWORD: 12345
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      barot-net:

  barot_migration:
    image: migrate/migrate:latest
    container_name: barot_migration
    entrypoint:
      - "sh"
      - "-c"
      - "`while ! /migrate -path /migrations -database postgres://postgres:12345@barot_pg:5432/postgres?sslmode=disable up; do sleep 1; done;`"
    volumes:
      - "./migrations:/migrations"
    depends_on:
      - barot_pg
    networks:
      barot-net:

networks:
  barot-net:
    name: barot-net
