version: '3.7'

services:
  barot_pg:
    image: postgres:11
    container_name: barot_pg
    environment:
      POSTGRES_PASSWORD: 12345
    expose:
      - "5432"
    networks:
      barot-test-net:

  barot_migration:
    image: migrate/migrate:latest
    container_name: barot_migration
    entrypoint:
      - "sh"
      - "-c"
      - "`while ! /migrate -path /migrations -database postgres://postgres:12345@barot_pg:5432/postgres?sslmode=disable up; do sleep 1; done; sleep 3600;`"
    volumes:
      - "./migrations:/migrations"
    depends_on:
      - barot_pg
    networks:
      barot-test-net:

  barot_rmq:
    image: rabbitmq:management-alpine
    container_name: barot_rmq
    ports:
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      barot-test-net:

  barot_api:
    image: barot_api:latest
    container_name: barot_api
    build: .
    environment:
      PG_DSN: postgres://postgres:12345@barot_pg:5432/postgres?sslmode=disable
      RMQ_DSN: amqp://guest:guest@barot_rmq:5672/
      HTTP_LISTEN: :80
    expose:
      - "80"
    ports:
      - "9090:80"
    depends_on:
      - barot_migration
      - barot_rmq
    networks:
      barot-test-net:

  barot_tests:
    container_name: barot_tests
    image: barot_tests:latest
    build: ./tests
    environment:
      API_URL: http://barot_api
    depends_on:
      - barot_api
    networks:
      barot-test-net:

networks:
  barot-test-net:
    name: barot-test-net
