name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: go mod download
        run: |
          go mod download

      - name: go fmt
        run: |
          go fmt ./...

      - name: go vet
        run: |
          go vet ./...

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./ v1.23.1
          ls -l
          ./golangci-lint run -v --enable-all

#      - name: go test
#        run: |
#          go test
#
#      - name: go test -race
#        run: |
#          go test -race
