name: test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: go mod download
        run: |
          go mod download

      - name: go fmt
        run: |
          if [[ $(go fmt ./...) ]]; then exit 1; fi;

      - name: go vet
        run: |
          go vet ./...

      - name: golangci-lint
        run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.23.6 golangci-lint run -v

      - name: go test
        run: |
          go test

      - name: go test -race
        run: |
          go test -race
